testsuite: disable tests using resource.get-xml
Problem: several tests fail when the fluxion resource module
aborts due to trying to access deprecated resource.get-xml RPC.

fluxion-resource is successfully loaded in these tests, but fails shortly
thereafter, causing subsequent tests to fail:

expecting success:
    load_resource subsystems=containment policy=high \
	load-format=hwloc load-allowlist=node,socket,core,gpu

2022-04-07T18:42:36.471631Z sched-fluxion-resource.err[0]: Unknown service method 'resource.get-xml'
2022-04-07T18:42:36.471651Z sched-fluxion-resource.err[0]: update_resource_db: grow_resource_db: Function not implemented
2022-04-07T18:42:36.471657Z sched-fluxion-resource.err[0]: update_resource: update_resource_db: Function not implemented
2022-04-07T18:42:36.471666Z sched-fluxion-resource.err[0]: populate_resource_db_acquire: update_resource: Function not implemented
2022-04-07T18:42:36.471671Z sched-fluxion-resource.err[0]: populate_resource_db: loading resources using resource.acquire
2022-04-07T18:42:36.471686Z sched-fluxion-resource.err[0]: init_resource_graph: error processing subsystems containment
2022-04-07T18:42:36.471697Z sched-fluxion-resource.err[0]: mod_main: can't initialize resource graph database
2022-04-07T18:42:36.471728Z sched-fluxion-resource.crit[0]: module exiting abnormally
ok 17 - load fluxion resource

expecting success:
    flux ion-resource match allocate ${jobspec_1socket_2gpu} &&
    flux ion-resource match allocate ${jobspec_1socket_2gpu} &&
    flux ion-resource match allocate ${jobspec_1socket_2gpu} &&
    flux ion-resource match allocate ${jobspec_1socket_2gpu} &&
    flux ion-resource match allocate ${jobspec_1socket_2gpu} &&
    flux ion-resource match allocate ${jobspec_1socket_2gpu} &&
    flux ion-resource match allocate ${jobspec_1socket_2gpu} &&
    flux ion-resource match allocate ${jobspec_1socket_2gpu} &&
    test_expect_code 16 flux ion-resource match allocate ${jobspec_1socket_2gpu}

OSError: error(38): No service matching sched-fluxion-resource.next_jobid is regist
not ok 18 - match allocate

Disable these tests pending follow up requested in #927