flux-tree: ensure flux-tree(-helper) work alongside other jobs
Problem: flux-tree-helper grabs the most recent N inactive jobs (with N
being the number of children launched by the root flux-tree invocation)
and attempts to grab a value from their guest KVSes, assuming those jobs
were all children of the flux-tree invocation.  If other jobs complete
during the teardown of the tree, the performance data collection will
fail with an error of the form:
```
KeyError: 'tree-perf not found under directory job.0000.000e.6b00.0000.guest.'
```
This occurs because flux-tree-helper attempts to access non-existant
perfomance data in the guest KVS of a non-flux-tree job that interleaved
with the flux-tree invocation.

Furthermore, if multiple flux-trees are invoked simultaneously,
erroneous performance data can be reported as the various
flux-tree-helper scripts collect performance data from the wrong
children.

Solution: Explicitly name each child submitted and then filter out
unrelated jobs when listing inactive jobs using the new `name` parameter
of the job-info service.  By default, flux-tree will name the child jobs
`flux-tree-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` where the Xs are data from
/dev/urandom converted into alphanumerics.  The user can optionally
override this behavior by passing `--job-name` to flux-tree with a
string name.

Test 1: invoke flux-tree, let it run to completion, run another job, then
manually re-invoke flux-tree-helper and test that the perf-output
matches the output from the flux-tree invocation.  If the first problem
described above is present, this test will fail since the
flux-tree-helper invocation will error out with the error listed above.n

Test 2: invoke flux-tree with a custom job-name, let it run to
completion, run another flux-tree (let it use the random name), then
manually re-invoke flux-tree-helper with the custom job-name and test
that the perf-output matches the output from the flux-tree invocation.
If the second problem described above is present, this test will fail
since the performance data will not match.