Fix broken && chains in t4014
Problem: fedora40 CI fails on t4014 due to """
  error: bug in the test script: broken &&-chain:
      load_feasibility
      flux dmesg -c | grep -q "File exists"
"""

Add && between successive statements in t4014.